"""Add avg_score to sessions

Revision ID: 0d412ec6f152
Revises: b5ac48a3421d
Create Date: 2025-05-19 09:56:24.687439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d412ec6f152'
down_revision: Union[str, None] = 'b5ac48a3421d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus_events')
    op.add_column('sessions', sa.Column('avg_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'avg_score')
    op.create_table('focus_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('focus_secs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('focus_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='focus_events_session_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='focus_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='focus_events_pkey')
    )
    # ### end Alembic commands ###
