"""Add Gemini fields to distractions

Revision ID: 3c8a6974499f
Revises: 55d68cf141a1
Create Date: 2025-05-13 17:39:08.464951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8a6974499f'
down_revision: Union[str, None] = '55d68cf141a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distractions', sa.Column('is_focused', sa.Boolean(), nullable=False))
    op.add_column('distractions', sa.Column('observed_behaviors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('distractions', sa.Column('explanation', sa.String(), nullable=True))
    op.alter_column('distractions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('distractions_session_id_fkey', 'distractions', type_='foreignkey')
    op.drop_column('distractions', 'hawon_park')
    op.drop_column('distractions', 'expires_at')
    op.drop_column('distractions', 'storage_path')
    op.drop_column('distractions', 'snapshot_url')
    op.drop_column('distractions', 'description')
    op.drop_column('distractions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distractions', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('snapshot_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('hawon_park', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('distractions_session_id_fkey', 'distractions', 'sessions', ['session_id'], ['id'])
    op.alter_column('distractions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('distractions', 'explanation')
    op.drop_column('distractions', 'observed_behaviors')
    op.drop_column('distractions', 'is_focused')
    # ### end Alembic commands ###
