"""add snapshot_url to distractions

Revision ID: 6a14db8d7ad7
Revises: 0d412ec6f152
Create Date: 2025-05-21 13:12:10.083268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a14db8d7ad7'
down_revision: Union[str, None] = '0d412ec6f152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distractions', sa.Column('snapshot_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distractions', 'snapshot_url')
    # ### end Alembic commands ###
